### ISSUE TITLE
Renewable resources ideas

### ISSUE THREAD

**Issue by notJyuu** [Ardub23/EverythingRenewable#1]
https://modrinth.com/datapack/sky-void-additions
^This datapack makes almost everything in the game renewable as well, but it is designed towards a skyblock world.
I believe you can take inspiration from this datapack. For example the sniffer could sniff out certain shards from certain biomes, as well as killing the dragon having a small chance to drop a dragon egg. 

The enchanted books can be obtained by villager gift as well

**Comment by Ardub23** [comment]
Thanks for the suggestions! I've put out a new version on Modrinth that adds ways to renew pottery sherds, dragon eggs, and enchanted books.
